name: Math Operations Backend Unit Testing Workflow
on:
  pull_request_review:
    types: [submitted]
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: >
      github.event.review.state == 'approved'
    steps:
      - name: Checkout Backend Repository Code
        uses: actions/checkout@v3
      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Project Dependencies
        run: npm ci
      - name: Execute Unit Tests
        run: npm run test
      - name: Post-Test Notification
        run: |
          echo "Unit tests completed successfully. Initiating the next steps in our testing strategy."

  auto-merge:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - name: Merge Pull Request
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_DELETE_BRANCH: "true"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_METHOD: "rebase"

  deployment:
    runs-on: ubuntu-latest
    needs: [auto-merge]
    steps:
      - name: Deployment Step
        run: |
          echo "Deploying the application from main branch..."

  trigger-e2e-tests:
    runs-on: ubuntu-latest
    needs: [deployment]
    steps:
      - name: Activate E2E Tests in Child Repository
        run: |
          curl -XPOST -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{ "event_type": "trigger-e2e-tests-event" }' \
          https://api.github.com/repos/<username>/math-operations-e2e/dispatches
